// Generated by jextract

package sh.adelessfox.vgmstream.libvgmstream;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;

/**
 * {@snippet lang=c :
 * struct {
 *     void *priv;
 *     const char *key;
 *     const char *val;
 * }
 * }
 */
public class libvgmstream_tags_t {

    libvgmstream_tags_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        libvgmstream_h.C_POINTER.withName("priv"),
        libvgmstream_h.C_POINTER.withName("key"),
        libvgmstream_h.C_POINTER.withName("val")
    ).withName("$anon$342:9");

    /**
     * The layout of this struct
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout priv$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("priv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *priv
     * }
     */
    public static AddressLayout priv$layout() {
        return priv$LAYOUT;
    }

    private static final long priv$OFFSET = $LAYOUT.byteOffset(groupElement("priv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *priv
     * }
     */
    public static long priv$offset() {
        return priv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *priv
     * }
     */
    public static MemorySegment priv(MemorySegment struct) {
        return struct.get(priv$LAYOUT, priv$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *priv
     * }
     */
    public static void priv(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(priv$LAYOUT, priv$OFFSET, fieldValue);
    }

    private static final AddressLayout key$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("key"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *key
     * }
     */
    public static AddressLayout key$layout() {
        return key$LAYOUT;
    }

    private static final long key$OFFSET = $LAYOUT.byteOffset(groupElement("key"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *key
     * }
     */
    public static long key$offset() {
        return key$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *key
     * }
     */
    public static MemorySegment key(MemorySegment struct) {
        return struct.get(key$LAYOUT, key$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *key
     * }
     */
    public static void key(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(key$LAYOUT, key$OFFSET, fieldValue);
    }

    private static final AddressLayout val$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("val"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *val
     * }
     */
    public static AddressLayout val$layout() {
        return val$LAYOUT;
    }

    private static final long val$OFFSET = $LAYOUT.byteOffset(groupElement("val"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *val
     * }
     */
    public static long val$offset() {
        return val$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *val
     * }
     */
    public static MemorySegment val(MemorySegment struct) {
        return struct.get(val$LAYOUT, val$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *val
     * }
     */
    public static void val(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(val$LAYOUT, val$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

