// Generated by jextract

package sh.adelessfox.vgmstream.libvgmstream;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfBoolean;

/**
 * {@snippet lang=c :
 * struct {
 *     _Bool force_title;
 *     _Bool subsong_range;
 *     _Bool remove_extension;
 *     _Bool remove_archive;
 *     const char *filename;
 * }
 * }
 */
public class libvgmstream_title_t {

    libvgmstream_title_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        libvgmstream_h.C_BOOL.withName("force_title"),
        libvgmstream_h.C_BOOL.withName("subsong_range"),
        libvgmstream_h.C_BOOL.withName("remove_extension"),
        libvgmstream_h.C_BOOL.withName("remove_archive"),
        MemoryLayout.paddingLayout(4),
        libvgmstream_h.C_POINTER.withName("filename")
    ).withName("$anon$311:9");

    /**
     * The layout of this struct
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfBoolean force_title$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("force_title"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool force_title
     * }
     */
    public static OfBoolean force_title$layout() {
        return force_title$LAYOUT;
    }

    private static final long force_title$OFFSET = $LAYOUT.byteOffset(groupElement("force_title"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool force_title
     * }
     */
    public static long force_title$offset() {
        return force_title$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool force_title
     * }
     */
    public static boolean force_title(MemorySegment struct) {
        return struct.get(force_title$LAYOUT, force_title$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool force_title
     * }
     */
    public static void force_title(MemorySegment struct, boolean fieldValue) {
        struct.set(force_title$LAYOUT, force_title$OFFSET, fieldValue);
    }

    private static final OfBoolean subsong_range$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("subsong_range"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool subsong_range
     * }
     */
    public static OfBoolean subsong_range$layout() {
        return subsong_range$LAYOUT;
    }

    private static final long subsong_range$OFFSET = $LAYOUT.byteOffset(groupElement("subsong_range"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool subsong_range
     * }
     */
    public static long subsong_range$offset() {
        return subsong_range$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool subsong_range
     * }
     */
    public static boolean subsong_range(MemorySegment struct) {
        return struct.get(subsong_range$LAYOUT, subsong_range$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool subsong_range
     * }
     */
    public static void subsong_range(MemorySegment struct, boolean fieldValue) {
        struct.set(subsong_range$LAYOUT, subsong_range$OFFSET, fieldValue);
    }

    private static final OfBoolean remove_extension$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("remove_extension"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool remove_extension
     * }
     */
    public static OfBoolean remove_extension$layout() {
        return remove_extension$LAYOUT;
    }

    private static final long remove_extension$OFFSET = $LAYOUT.byteOffset(groupElement("remove_extension"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool remove_extension
     * }
     */
    public static long remove_extension$offset() {
        return remove_extension$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool remove_extension
     * }
     */
    public static boolean remove_extension(MemorySegment struct) {
        return struct.get(remove_extension$LAYOUT, remove_extension$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool remove_extension
     * }
     */
    public static void remove_extension(MemorySegment struct, boolean fieldValue) {
        struct.set(remove_extension$LAYOUT, remove_extension$OFFSET, fieldValue);
    }

    private static final OfBoolean remove_archive$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("remove_archive"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool remove_archive
     * }
     */
    public static OfBoolean remove_archive$layout() {
        return remove_archive$LAYOUT;
    }

    private static final long remove_archive$OFFSET = $LAYOUT.byteOffset(groupElement("remove_archive"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool remove_archive
     * }
     */
    public static long remove_archive$offset() {
        return remove_archive$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool remove_archive
     * }
     */
    public static boolean remove_archive(MemorySegment struct) {
        return struct.get(remove_archive$LAYOUT, remove_archive$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool remove_archive
     * }
     */
    public static void remove_archive(MemorySegment struct, boolean fieldValue) {
        struct.set(remove_archive$LAYOUT, remove_archive$OFFSET, fieldValue);
    }

    private static final AddressLayout filename$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("filename"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *filename
     * }
     */
    public static AddressLayout filename$layout() {
        return filename$LAYOUT;
    }

    private static final long filename$OFFSET = $LAYOUT.byteOffset(groupElement("filename"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *filename
     * }
     */
    public static long filename$offset() {
        return filename$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *filename
     * }
     */
    public static MemorySegment filename(MemorySegment struct) {
        return struct.get(filename$LAYOUT, filename$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *filename
     * }
     */
    public static void filename(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(filename$LAYOUT, filename$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

