// Generated by jextract

package sh.adelessfox.vgmstream.libvgmstream;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SymbolLookup;
import java.lang.invoke.MethodHandle;
import java.util.Locale;

public class libvgmstream_h extends libvgmstream_h$shared {
    static {
        var isWindows = System.getProperty("os.name").toLowerCase(Locale.ENGLISH).startsWith("windows");
        var prefix = isWindows ? "lib" : "";
        System.loadLibrary(prefix + "atrac9");
        System.loadLibrary(prefix + "vgmstream");
        System.loadLibrary(prefix + "vorbis");
    }

    libvgmstream_h() {
        // Should not be called directly
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
        .or(Linker.nativeLinker().defaultLookup());

    private static class libstreamfile_close {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libstreamfile_close");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * void libstreamfile_close(libstreamfile_t *libsf)
     *}
     */
    public static FunctionDescriptor libstreamfile_close$descriptor() {
        return libstreamfile_close.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * void libstreamfile_close(libstreamfile_t *libsf)
     *}
     */
    public static MethodHandle libstreamfile_close$handle() {
        return libstreamfile_close.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * void libstreamfile_close(libstreamfile_t *libsf)
     *}
     */
    public static MemorySegment libstreamfile_close$address() {
        return libstreamfile_close.ADDR;
    }

    /**
     * {@snippet lang = c:
     * void libstreamfile_close(libstreamfile_t *libsf)
     *}
     */
    public static void libstreamfile_close(MemorySegment libsf) {
        var mh$ = libstreamfile_close.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libstreamfile_close", libsf);
            }
            mh$.invokeExact(libsf);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libstreamfile_open_from_stdio {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libstreamfile_open_from_stdio");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * libstreamfile_t *libstreamfile_open_from_stdio(const char *filename)
     *}
     */
    public static FunctionDescriptor libstreamfile_open_from_stdio$descriptor() {
        return libstreamfile_open_from_stdio.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * libstreamfile_t *libstreamfile_open_from_stdio(const char *filename)
     *}
     */
    public static MethodHandle libstreamfile_open_from_stdio$handle() {
        return libstreamfile_open_from_stdio.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * libstreamfile_t *libstreamfile_open_from_stdio(const char *filename)
     *}
     */
    public static MemorySegment libstreamfile_open_from_stdio$address() {
        return libstreamfile_open_from_stdio.ADDR;
    }

    /**
     * {@snippet lang = c:
     * libstreamfile_t *libstreamfile_open_from_stdio(const char *filename)
     *}
     */
    public static MemorySegment libstreamfile_open_from_stdio(MemorySegment filename) {
        var mh$ = libstreamfile_open_from_stdio.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libstreamfile_open_from_stdio", filename);
            }
            return (MemorySegment) mh$.invokeExact(filename);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libstreamfile_open_from_file {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libstreamfile_open_from_file");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * libstreamfile_t *libstreamfile_open_from_file(void *file, const char *filename)
     *}
     */
    public static FunctionDescriptor libstreamfile_open_from_file$descriptor() {
        return libstreamfile_open_from_file.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * libstreamfile_t *libstreamfile_open_from_file(void *file, const char *filename)
     *}
     */
    public static MethodHandle libstreamfile_open_from_file$handle() {
        return libstreamfile_open_from_file.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * libstreamfile_t *libstreamfile_open_from_file(void *file, const char *filename)
     *}
     */
    public static MemorySegment libstreamfile_open_from_file$address() {
        return libstreamfile_open_from_file.ADDR;
    }

    /**
     * {@snippet lang = c:
     * libstreamfile_t *libstreamfile_open_from_file(void *file, const char *filename)
     *}
     */
    public static MemorySegment libstreamfile_open_from_file(MemorySegment file, MemorySegment filename) {
        var mh$ = libstreamfile_open_from_file.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libstreamfile_open_from_file", file, filename);
            }
            return (MemorySegment) mh$.invokeExact(file, filename);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libstreamfile_open_buffered {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libstreamfile_open_buffered");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * libstreamfile_t *libstreamfile_open_buffered(libstreamfile_t *ext_libsf)
     *}
     */
    public static FunctionDescriptor libstreamfile_open_buffered$descriptor() {
        return libstreamfile_open_buffered.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * libstreamfile_t *libstreamfile_open_buffered(libstreamfile_t *ext_libsf)
     *}
     */
    public static MethodHandle libstreamfile_open_buffered$handle() {
        return libstreamfile_open_buffered.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * libstreamfile_t *libstreamfile_open_buffered(libstreamfile_t *ext_libsf)
     *}
     */
    public static MemorySegment libstreamfile_open_buffered$address() {
        return libstreamfile_open_buffered.ADDR;
    }

    /**
     * {@snippet lang = c:
     * libstreamfile_t *libstreamfile_open_buffered(libstreamfile_t *ext_libsf)
     *}
     */
    public static MemorySegment libstreamfile_open_buffered(MemorySegment ext_libsf) {
        var mh$ = libstreamfile_open_buffered.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libstreamfile_open_buffered", ext_libsf);
            }
            return (MemorySegment) mh$.invokeExact(ext_libsf);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_get_version {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_INT);

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_get_version");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * uint32_t libvgmstream_get_version()
     *}
     */
    public static FunctionDescriptor libvgmstream_get_version$descriptor() {
        return libvgmstream_get_version.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * uint32_t libvgmstream_get_version()
     *}
     */
    public static MethodHandle libvgmstream_get_version$handle() {
        return libvgmstream_get_version.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * uint32_t libvgmstream_get_version()
     *}
     */
    public static MemorySegment libvgmstream_get_version$address() {
        return libvgmstream_get_version.ADDR;
    }

    /**
     * {@snippet lang = c:
     * uint32_t libvgmstream_get_version()
     *}
     */
    public static int libvgmstream_get_version() {
        var mh$ = libvgmstream_get_version.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_get_version");
            }
            return (int) mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static final int LIBVGMSTREAM_SFMT_PCM16 = (int) 1L;

    /**
     * {@snippet lang = c:
     * enum <anonymous>.LIBVGMSTREAM_SFMT_PCM16 = 1
     *}
     */
    public static int LIBVGMSTREAM_SFMT_PCM16() {
        return LIBVGMSTREAM_SFMT_PCM16;
    }

    private static final int LIBVGMSTREAM_SFMT_PCM24 = (int) 2L;

    /**
     * {@snippet lang = c:
     * enum <anonymous>.LIBVGMSTREAM_SFMT_PCM24 = 2
     *}
     */
    public static int LIBVGMSTREAM_SFMT_PCM24() {
        return LIBVGMSTREAM_SFMT_PCM24;
    }

    private static final int LIBVGMSTREAM_SFMT_PCM32 = (int) 3L;

    /**
     * {@snippet lang = c:
     * enum <anonymous>.LIBVGMSTREAM_SFMT_PCM32 = 3
     *}
     */
    public static int LIBVGMSTREAM_SFMT_PCM32() {
        return LIBVGMSTREAM_SFMT_PCM32;
    }

    private static final int LIBVGMSTREAM_SFMT_FLOAT = (int) 4L;

    /**
     * {@snippet lang = c:
     * enum <anonymous>.LIBVGMSTREAM_SFMT_FLOAT = 4
     *}
     */
    public static int LIBVGMSTREAM_SFMT_FLOAT() {
        return LIBVGMSTREAM_SFMT_FLOAT;
    }

    private static class libvgmstream_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_POINTER);

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * libvgmstream_t *libvgmstream_init()
     *}
     */
    public static FunctionDescriptor libvgmstream_init$descriptor() {
        return libvgmstream_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * libvgmstream_t *libvgmstream_init()
     *}
     */
    public static MethodHandle libvgmstream_init$handle() {
        return libvgmstream_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * libvgmstream_t *libvgmstream_init()
     *}
     */
    public static MemorySegment libvgmstream_init$address() {
        return libvgmstream_init.ADDR;
    }

    /**
     * {@snippet lang = c:
     * libvgmstream_t *libvgmstream_init()
     *}
     */
    public static MemorySegment libvgmstream_init() {
        var mh$ = libvgmstream_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_init");
            }
            return (MemorySegment) mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * void libvgmstream_free(libvgmstream_t *lib)
     *}
     */
    public static FunctionDescriptor libvgmstream_free$descriptor() {
        return libvgmstream_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * void libvgmstream_free(libvgmstream_t *lib)
     *}
     */
    public static MethodHandle libvgmstream_free$handle() {
        return libvgmstream_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * void libvgmstream_free(libvgmstream_t *lib)
     *}
     */
    public static MemorySegment libvgmstream_free$address() {
        return libvgmstream_free.ADDR;
    }

    /**
     * {@snippet lang = c:
     * void libvgmstream_free(libvgmstream_t *lib)
     *}
     */
    public static void libvgmstream_free(MemorySegment lib) {
        var mh$ = libvgmstream_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_free", lib);
            }
            mh$.invokeExact(lib);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_setup {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_setup");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * void libvgmstream_setup(libvgmstream_t *lib, libvgmstream_config_t *cfg)
     *}
     */
    public static FunctionDescriptor libvgmstream_setup$descriptor() {
        return libvgmstream_setup.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * void libvgmstream_setup(libvgmstream_t *lib, libvgmstream_config_t *cfg)
     *}
     */
    public static MethodHandle libvgmstream_setup$handle() {
        return libvgmstream_setup.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * void libvgmstream_setup(libvgmstream_t *lib, libvgmstream_config_t *cfg)
     *}
     */
    public static MemorySegment libvgmstream_setup$address() {
        return libvgmstream_setup.ADDR;
    }

    /**
     * {@snippet lang = c:
     * void libvgmstream_setup(libvgmstream_t *lib, libvgmstream_config_t *cfg)
     *}
     */
    public static void libvgmstream_setup(MemorySegment lib, MemorySegment cfg) {
        var mh$ = libvgmstream_setup.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_setup", lib, cfg);
            }
            mh$.invokeExact(lib, cfg);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_open_stream {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_INT,
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_open_stream");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * int libvgmstream_open_stream(libvgmstream_t *lib, libstreamfile_t *libsf, int subsong)
     *}
     */
    public static FunctionDescriptor libvgmstream_open_stream$descriptor() {
        return libvgmstream_open_stream.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * int libvgmstream_open_stream(libvgmstream_t *lib, libstreamfile_t *libsf, int subsong)
     *}
     */
    public static MethodHandle libvgmstream_open_stream$handle() {
        return libvgmstream_open_stream.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * int libvgmstream_open_stream(libvgmstream_t *lib, libstreamfile_t *libsf, int subsong)
     *}
     */
    public static MemorySegment libvgmstream_open_stream$address() {
        return libvgmstream_open_stream.ADDR;
    }

    /**
     * {@snippet lang = c:
     * int libvgmstream_open_stream(libvgmstream_t *lib, libstreamfile_t *libsf, int subsong)
     *}
     */
    public static int libvgmstream_open_stream(MemorySegment lib, MemorySegment libsf, int subsong) {
        var mh$ = libvgmstream_open_stream.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_open_stream", lib, libsf, subsong);
            }
            return (int) mh$.invokeExact(lib, libsf, subsong);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_close_stream {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_close_stream");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * void libvgmstream_close_stream(libvgmstream_t *lib)
     *}
     */
    public static FunctionDescriptor libvgmstream_close_stream$descriptor() {
        return libvgmstream_close_stream.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * void libvgmstream_close_stream(libvgmstream_t *lib)
     *}
     */
    public static MethodHandle libvgmstream_close_stream$handle() {
        return libvgmstream_close_stream.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * void libvgmstream_close_stream(libvgmstream_t *lib)
     *}
     */
    public static MemorySegment libvgmstream_close_stream$address() {
        return libvgmstream_close_stream.ADDR;
    }

    /**
     * {@snippet lang = c:
     * void libvgmstream_close_stream(libvgmstream_t *lib)
     *}
     */
    public static void libvgmstream_close_stream(MemorySegment lib) {
        var mh$ = libvgmstream_close_stream.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_close_stream", lib);
            }
            mh$.invokeExact(lib);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_render {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_INT,
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_render");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * int libvgmstream_render(libvgmstream_t *lib)
     *}
     */
    public static FunctionDescriptor libvgmstream_render$descriptor() {
        return libvgmstream_render.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * int libvgmstream_render(libvgmstream_t *lib)
     *}
     */
    public static MethodHandle libvgmstream_render$handle() {
        return libvgmstream_render.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * int libvgmstream_render(libvgmstream_t *lib)
     *}
     */
    public static MemorySegment libvgmstream_render$address() {
        return libvgmstream_render.ADDR;
    }

    /**
     * {@snippet lang = c:
     * int libvgmstream_render(libvgmstream_t *lib)
     *}
     */
    public static int libvgmstream_render(MemorySegment lib) {
        var mh$ = libvgmstream_render.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_render", lib);
            }
            return (int) mh$.invokeExact(lib);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_fill {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_INT,
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_fill");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * int libvgmstream_fill(libvgmstream_t *lib, void *buf, int buf_samples)
     *}
     */
    public static FunctionDescriptor libvgmstream_fill$descriptor() {
        return libvgmstream_fill.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * int libvgmstream_fill(libvgmstream_t *lib, void *buf, int buf_samples)
     *}
     */
    public static MethodHandle libvgmstream_fill$handle() {
        return libvgmstream_fill.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * int libvgmstream_fill(libvgmstream_t *lib, void *buf, int buf_samples)
     *}
     */
    public static MemorySegment libvgmstream_fill$address() {
        return libvgmstream_fill.ADDR;
    }

    /**
     * {@snippet lang = c:
     * int libvgmstream_fill(libvgmstream_t *lib, void *buf, int buf_samples)
     *}
     */
    public static int libvgmstream_fill(MemorySegment lib, MemorySegment buf, int buf_samples) {
        var mh$ = libvgmstream_fill.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_fill", lib, buf, buf_samples);
            }
            return (int) mh$.invokeExact(lib, buf, buf_samples);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_get_play_position {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_LONG_LONG,
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_get_play_position");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * int64_t libvgmstream_get_play_position(libvgmstream_t *lib)
     *}
     */
    public static FunctionDescriptor libvgmstream_get_play_position$descriptor() {
        return libvgmstream_get_play_position.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * int64_t libvgmstream_get_play_position(libvgmstream_t *lib)
     *}
     */
    public static MethodHandle libvgmstream_get_play_position$handle() {
        return libvgmstream_get_play_position.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * int64_t libvgmstream_get_play_position(libvgmstream_t *lib)
     *}
     */
    public static MemorySegment libvgmstream_get_play_position$address() {
        return libvgmstream_get_play_position.ADDR;
    }

    /**
     * {@snippet lang = c:
     * int64_t libvgmstream_get_play_position(libvgmstream_t *lib)
     *}
     */
    public static long libvgmstream_get_play_position(MemorySegment lib) {
        var mh$ = libvgmstream_get_play_position.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_get_play_position", lib);
            }
            return (long) mh$.invokeExact(lib);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_seek {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_seek");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * void libvgmstream_seek(libvgmstream_t *lib, int64_t sample)
     *}
     */
    public static FunctionDescriptor libvgmstream_seek$descriptor() {
        return libvgmstream_seek.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * void libvgmstream_seek(libvgmstream_t *lib, int64_t sample)
     *}
     */
    public static MethodHandle libvgmstream_seek$handle() {
        return libvgmstream_seek.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * void libvgmstream_seek(libvgmstream_t *lib, int64_t sample)
     *}
     */
    public static MemorySegment libvgmstream_seek$address() {
        return libvgmstream_seek.ADDR;
    }

    /**
     * {@snippet lang = c:
     * void libvgmstream_seek(libvgmstream_t *lib, int64_t sample)
     *}
     */
    public static void libvgmstream_seek(MemorySegment lib, long sample) {
        var mh$ = libvgmstream_seek.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_seek", lib, sample);
            }
            mh$.invokeExact(lib, sample);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_reset {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_reset");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * void libvgmstream_reset(libvgmstream_t *lib)
     *}
     */
    public static FunctionDescriptor libvgmstream_reset$descriptor() {
        return libvgmstream_reset.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * void libvgmstream_reset(libvgmstream_t *lib)
     *}
     */
    public static MethodHandle libvgmstream_reset$handle() {
        return libvgmstream_reset.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * void libvgmstream_reset(libvgmstream_t *lib)
     *}
     */
    public static MemorySegment libvgmstream_reset$address() {
        return libvgmstream_reset.ADDR;
    }

    /**
     * {@snippet lang = c:
     * void libvgmstream_reset(libvgmstream_t *lib)
     *}
     */
    public static void libvgmstream_reset(MemorySegment lib) {
        var mh$ = libvgmstream_reset.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_reset", lib);
            }
            mh$.invokeExact(lib);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_create {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_INT,
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_create");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * libvgmstream_t *libvgmstream_create(libstreamfile_t *libsf, int subsong, libvgmstream_config_t *cfg)
     *}
     */
    public static FunctionDescriptor libvgmstream_create$descriptor() {
        return libvgmstream_create.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * libvgmstream_t *libvgmstream_create(libstreamfile_t *libsf, int subsong, libvgmstream_config_t *cfg)
     *}
     */
    public static MethodHandle libvgmstream_create$handle() {
        return libvgmstream_create.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * libvgmstream_t *libvgmstream_create(libstreamfile_t *libsf, int subsong, libvgmstream_config_t *cfg)
     *}
     */
    public static MemorySegment libvgmstream_create$address() {
        return libvgmstream_create.ADDR;
    }

    /**
     * {@snippet lang = c:
     * libvgmstream_t *libvgmstream_create(libstreamfile_t *libsf, int subsong, libvgmstream_config_t *cfg)
     *}
     */
    public static MemorySegment libvgmstream_create(MemorySegment libsf, int subsong, MemorySegment cfg) {
        var mh$ = libvgmstream_create.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_create", libsf, subsong, cfg);
            }
            return (MemorySegment) mh$.invokeExact(libsf, subsong, cfg);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static final int LIBVGMSTREAM_LOG_LEVEL_ALL = (int) 0L;

    /**
     * {@snippet lang = c:
     * enum <anonymous>.LIBVGMSTREAM_LOG_LEVEL_ALL = 0
     *}
     */
    public static int LIBVGMSTREAM_LOG_LEVEL_ALL() {
        return LIBVGMSTREAM_LOG_LEVEL_ALL;
    }

    private static final int LIBVGMSTREAM_LOG_LEVEL_DEBUG = (int) 20L;

    /**
     * {@snippet lang = c:
     * enum <anonymous>.LIBVGMSTREAM_LOG_LEVEL_DEBUG = 20
     *}
     */
    public static int LIBVGMSTREAM_LOG_LEVEL_DEBUG() {
        return LIBVGMSTREAM_LOG_LEVEL_DEBUG;
    }

    private static final int LIBVGMSTREAM_LOG_LEVEL_INFO = (int) 30L;

    /**
     * {@snippet lang = c:
     * enum <anonymous>.LIBVGMSTREAM_LOG_LEVEL_INFO = 30
     *}
     */
    public static int LIBVGMSTREAM_LOG_LEVEL_INFO() {
        return LIBVGMSTREAM_LOG_LEVEL_INFO;
    }

    private static final int LIBVGMSTREAM_LOG_LEVEL_NONE = (int) 100L;

    /**
     * {@snippet lang = c:
     * enum <anonymous>.LIBVGMSTREAM_LOG_LEVEL_NONE = 100
     *}
     */
    public static int LIBVGMSTREAM_LOG_LEVEL_NONE() {
        return LIBVGMSTREAM_LOG_LEVEL_NONE;
    }

    private static class libvgmstream_set_log {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            libvgmstream_h.C_INT,
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_set_log");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * void libvgmstream_set_log(libvgmstream_loglevel_t level, void (*callback)(int, const char *))
     *}
     */
    public static FunctionDescriptor libvgmstream_set_log$descriptor() {
        return libvgmstream_set_log.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * void libvgmstream_set_log(libvgmstream_loglevel_t level, void (*callback)(int, const char *))
     *}
     */
    public static MethodHandle libvgmstream_set_log$handle() {
        return libvgmstream_set_log.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * void libvgmstream_set_log(libvgmstream_loglevel_t level, void (*callback)(int, const char *))
     *}
     */
    public static MemorySegment libvgmstream_set_log$address() {
        return libvgmstream_set_log.ADDR;
    }

    /**
     * {@snippet lang = c:
     * void libvgmstream_set_log(libvgmstream_loglevel_t level, void (*callback)(int, const char *))
     *}
     */
    public static void libvgmstream_set_log(int level, MemorySegment callback) {
        var mh$ = libvgmstream_set_log.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_set_log", level, callback);
            }
            mh$.invokeExact(level, callback);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_get_extensions {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_get_extensions");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * const char **libvgmstream_get_extensions(int *size)
     *}
     */
    public static FunctionDescriptor libvgmstream_get_extensions$descriptor() {
        return libvgmstream_get_extensions.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * const char **libvgmstream_get_extensions(int *size)
     *}
     */
    public static MethodHandle libvgmstream_get_extensions$handle() {
        return libvgmstream_get_extensions.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * const char **libvgmstream_get_extensions(int *size)
     *}
     */
    public static MemorySegment libvgmstream_get_extensions$address() {
        return libvgmstream_get_extensions.ADDR;
    }

    /**
     * {@snippet lang = c:
     * const char **libvgmstream_get_extensions(int *size)
     *}
     */
    public static MemorySegment libvgmstream_get_extensions(MemorySegment size) {
        var mh$ = libvgmstream_get_extensions.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_get_extensions", size);
            }
            return (MemorySegment) mh$.invokeExact(size);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_get_common_extensions {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_get_common_extensions");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * const char **libvgmstream_get_common_extensions(int *size)
     *}
     */
    public static FunctionDescriptor libvgmstream_get_common_extensions$descriptor() {
        return libvgmstream_get_common_extensions.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * const char **libvgmstream_get_common_extensions(int *size)
     *}
     */
    public static MethodHandle libvgmstream_get_common_extensions$handle() {
        return libvgmstream_get_common_extensions.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * const char **libvgmstream_get_common_extensions(int *size)
     *}
     */
    public static MemorySegment libvgmstream_get_common_extensions$address() {
        return libvgmstream_get_common_extensions.ADDR;
    }

    /**
     * {@snippet lang = c:
     * const char **libvgmstream_get_common_extensions(int *size)
     *}
     */
    public static MemorySegment libvgmstream_get_common_extensions(MemorySegment size) {
        var mh$ = libvgmstream_get_common_extensions.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_get_common_extensions", size);
            }
            return (MemorySegment) mh$.invokeExact(size);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_is_valid {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_BOOL,
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_is_valid");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * _Bool libvgmstream_is_valid(const char *filename, libvgmstream_valid_t *cfg)
     *}
     */
    public static FunctionDescriptor libvgmstream_is_valid$descriptor() {
        return libvgmstream_is_valid.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * _Bool libvgmstream_is_valid(const char *filename, libvgmstream_valid_t *cfg)
     *}
     */
    public static MethodHandle libvgmstream_is_valid$handle() {
        return libvgmstream_is_valid.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * _Bool libvgmstream_is_valid(const char *filename, libvgmstream_valid_t *cfg)
     *}
     */
    public static MemorySegment libvgmstream_is_valid$address() {
        return libvgmstream_is_valid.ADDR;
    }

    /**
     * {@snippet lang = c:
     * _Bool libvgmstream_is_valid(const char *filename, libvgmstream_valid_t *cfg)
     *}
     */
    public static boolean libvgmstream_is_valid(MemorySegment filename, MemorySegment cfg) {
        var mh$ = libvgmstream_is_valid.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_is_valid", filename, cfg);
            }
            return (boolean) mh$.invokeExact(filename, cfg);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_get_title {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_INT,
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_get_title");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * int libvgmstream_get_title(libvgmstream_t *lib, libvgmstream_title_t *cfg, char *buf, int buf_len)
     *}
     */
    public static FunctionDescriptor libvgmstream_get_title$descriptor() {
        return libvgmstream_get_title.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * int libvgmstream_get_title(libvgmstream_t *lib, libvgmstream_title_t *cfg, char *buf, int buf_len)
     *}
     */
    public static MethodHandle libvgmstream_get_title$handle() {
        return libvgmstream_get_title.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * int libvgmstream_get_title(libvgmstream_t *lib, libvgmstream_title_t *cfg, char *buf, int buf_len)
     *}
     */
    public static MemorySegment libvgmstream_get_title$address() {
        return libvgmstream_get_title.ADDR;
    }

    /**
     * {@snippet lang = c:
     * int libvgmstream_get_title(libvgmstream_t *lib, libvgmstream_title_t *cfg, char *buf, int buf_len)
     *}
     */
    public static int libvgmstream_get_title(MemorySegment lib, MemorySegment cfg, MemorySegment buf, int buf_len) {
        var mh$ = libvgmstream_get_title.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_get_title", lib, cfg, buf, buf_len);
            }
            return (int) mh$.invokeExact(lib, cfg, buf, buf_len);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_format_describe {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_INT,
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_format_describe");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * int libvgmstream_format_describe(libvgmstream_t *lib, char *dst, int dst_size)
     *}
     */
    public static FunctionDescriptor libvgmstream_format_describe$descriptor() {
        return libvgmstream_format_describe.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * int libvgmstream_format_describe(libvgmstream_t *lib, char *dst, int dst_size)
     *}
     */
    public static MethodHandle libvgmstream_format_describe$handle() {
        return libvgmstream_format_describe.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * int libvgmstream_format_describe(libvgmstream_t *lib, char *dst, int dst_size)
     *}
     */
    public static MemorySegment libvgmstream_format_describe$address() {
        return libvgmstream_format_describe.ADDR;
    }

    /**
     * {@snippet lang = c:
     * int libvgmstream_format_describe(libvgmstream_t *lib, char *dst, int dst_size)
     *}
     */
    public static int libvgmstream_format_describe(MemorySegment lib, MemorySegment dst, int dst_size) {
        var mh$ = libvgmstream_format_describe.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_format_describe", lib, dst, dst_size);
            }
            return (int) mh$.invokeExact(lib, dst, dst_size);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_is_virtual_filename {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_BOOL,
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_is_virtual_filename");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * _Bool libvgmstream_is_virtual_filename(const char *filename)
     *}
     */
    public static FunctionDescriptor libvgmstream_is_virtual_filename$descriptor() {
        return libvgmstream_is_virtual_filename.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * _Bool libvgmstream_is_virtual_filename(const char *filename)
     *}
     */
    public static MethodHandle libvgmstream_is_virtual_filename$handle() {
        return libvgmstream_is_virtual_filename.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * _Bool libvgmstream_is_virtual_filename(const char *filename)
     *}
     */
    public static MemorySegment libvgmstream_is_virtual_filename$address() {
        return libvgmstream_is_virtual_filename.ADDR;
    }

    /**
     * {@snippet lang = c:
     * _Bool libvgmstream_is_virtual_filename(const char *filename)
     *}
     */
    public static boolean libvgmstream_is_virtual_filename(MemorySegment filename) {
        var mh$ = libvgmstream_is_virtual_filename.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_is_virtual_filename", filename);
            }
            return (boolean) mh$.invokeExact(filename);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_tags_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_tags_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * libvgmstream_tags_t *libvgmstream_tags_init(libstreamfile_t *libsf)
     *}
     */
    public static FunctionDescriptor libvgmstream_tags_init$descriptor() {
        return libvgmstream_tags_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * libvgmstream_tags_t *libvgmstream_tags_init(libstreamfile_t *libsf)
     *}
     */
    public static MethodHandle libvgmstream_tags_init$handle() {
        return libvgmstream_tags_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * libvgmstream_tags_t *libvgmstream_tags_init(libstreamfile_t *libsf)
     *}
     */
    public static MemorySegment libvgmstream_tags_init$address() {
        return libvgmstream_tags_init.ADDR;
    }

    /**
     * {@snippet lang = c:
     * libvgmstream_tags_t *libvgmstream_tags_init(libstreamfile_t *libsf)
     *}
     */
    public static MemorySegment libvgmstream_tags_init(MemorySegment libsf) {
        var mh$ = libvgmstream_tags_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_tags_init", libsf);
            }
            return (MemorySegment) mh$.invokeExact(libsf);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_tags_find {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            libvgmstream_h.C_POINTER,
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_tags_find");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * void libvgmstream_tags_find(libvgmstream_tags_t *tags, const char *target_filename)
     *}
     */
    public static FunctionDescriptor libvgmstream_tags_find$descriptor() {
        return libvgmstream_tags_find.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * void libvgmstream_tags_find(libvgmstream_tags_t *tags, const char *target_filename)
     *}
     */
    public static MethodHandle libvgmstream_tags_find$handle() {
        return libvgmstream_tags_find.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * void libvgmstream_tags_find(libvgmstream_tags_t *tags, const char *target_filename)
     *}
     */
    public static MemorySegment libvgmstream_tags_find$address() {
        return libvgmstream_tags_find.ADDR;
    }

    /**
     * {@snippet lang = c:
     * void libvgmstream_tags_find(libvgmstream_tags_t *tags, const char *target_filename)
     *}
     */
    public static void libvgmstream_tags_find(MemorySegment tags, MemorySegment target_filename) {
        var mh$ = libvgmstream_tags_find.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_tags_find", tags, target_filename);
            }
            mh$.invokeExact(tags, target_filename);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_tags_next_tag {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libvgmstream_h.C_BOOL,
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_tags_next_tag");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * _Bool libvgmstream_tags_next_tag(libvgmstream_tags_t *tags)
     *}
     */
    public static FunctionDescriptor libvgmstream_tags_next_tag$descriptor() {
        return libvgmstream_tags_next_tag.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * _Bool libvgmstream_tags_next_tag(libvgmstream_tags_t *tags)
     *}
     */
    public static MethodHandle libvgmstream_tags_next_tag$handle() {
        return libvgmstream_tags_next_tag.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * _Bool libvgmstream_tags_next_tag(libvgmstream_tags_t *tags)
     *}
     */
    public static MemorySegment libvgmstream_tags_next_tag$address() {
        return libvgmstream_tags_next_tag.ADDR;
    }

    /**
     * {@snippet lang = c:
     * _Bool libvgmstream_tags_next_tag(libvgmstream_tags_t *tags)
     *}
     */
    public static boolean libvgmstream_tags_next_tag(MemorySegment tags) {
        var mh$ = libvgmstream_tags_next_tag.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_tags_next_tag", tags);
            }
            return (boolean) mh$.invokeExact(tags);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class libvgmstream_tags_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            libvgmstream_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("libvgmstream_tags_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * void libvgmstream_tags_free(libvgmstream_tags_t *tags)
     *}
     */
    public static FunctionDescriptor libvgmstream_tags_free$descriptor() {
        return libvgmstream_tags_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * void libvgmstream_tags_free(libvgmstream_tags_t *tags)
     *}
     */
    public static MethodHandle libvgmstream_tags_free$handle() {
        return libvgmstream_tags_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * void libvgmstream_tags_free(libvgmstream_tags_t *tags)
     *}
     */
    public static MemorySegment libvgmstream_tags_free$address() {
        return libvgmstream_tags_free.ADDR;
    }

    /**
     * {@snippet lang = c:
     * void libvgmstream_tags_free(libvgmstream_tags_t *tags)
     *}
     */
    public static void libvgmstream_tags_free(MemorySegment tags) {
        var mh$ = libvgmstream_tags_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("libvgmstream_tags_free", tags);
            }
            mh$.invokeExact(tags);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static final int _VCRUNTIME_DISABLED_WARNINGS = (int) 4514L;

    /**
     * {@snippet lang = c:
     * #define _VCRUNTIME_DISABLED_WARNINGS 4514
     *}
     */
    public static int _VCRUNTIME_DISABLED_WARNINGS() {
        return _VCRUNTIME_DISABLED_WARNINGS;
    }

    private static final MemorySegment NULL = MemorySegment.ofAddress(0L);

    /**
     * {@snippet lang = c:
     * #define NULL (void*) 0
     *}
     */
    public static MemorySegment NULL() {
        return NULL;
    }

    private static final int INT8_MIN = (int) -128L;

    /**
     * {@snippet lang = c:
     * #define INT8_MIN -128
     *}
     */
    public static int INT8_MIN() {
        return INT8_MIN;
    }

    private static final int INT16_MIN = (int) -32768L;

    /**
     * {@snippet lang = c:
     * #define INT16_MIN -32768
     *}
     */
    public static int INT16_MIN() {
        return INT16_MIN;
    }

    private static final int INT32_MIN = (int) -2147483648L;

    /**
     * {@snippet lang = c:
     * #define INT32_MIN -2147483648
     *}
     */
    public static int INT32_MIN() {
        return INT32_MIN;
    }

    private static final long INT64_MIN = -9223372036854775808L;

    /**
     * {@snippet lang = c:
     * #define INT64_MIN -9223372036854775808
     *}
     */
    public static long INT64_MIN() {
        return INT64_MIN;
    }

    private static final byte INT8_MAX = (byte) 127L;

    /**
     * {@snippet lang = c:
     * #define INT8_MAX 127
     *}
     */
    public static byte INT8_MAX() {
        return INT8_MAX;
    }

    private static final short INT16_MAX = (short) 32767L;

    /**
     * {@snippet lang = c:
     * #define INT16_MAX 32767
     *}
     */
    public static short INT16_MAX() {
        return INT16_MAX;
    }

    private static final int INT32_MAX = (int) 2147483647L;

    /**
     * {@snippet lang = c:
     * #define INT32_MAX 2147483647
     *}
     */
    public static int INT32_MAX() {
        return INT32_MAX;
    }

    private static final long INT64_MAX = 9223372036854775807L;

    /**
     * {@snippet lang = c:
     * #define INT64_MAX 9223372036854775807
     *}
     */
    public static long INT64_MAX() {
        return INT64_MAX;
    }

    private static final byte UINT8_MAX = (byte) 255L;

    /**
     * {@snippet lang = c:
     * #define UINT8_MAX 255
     *}
     */
    public static byte UINT8_MAX() {
        return UINT8_MAX;
    }

    private static final short UINT16_MAX = (short) 65535L;

    /**
     * {@snippet lang = c:
     * #define UINT16_MAX 65535
     *}
     */
    public static short UINT16_MAX() {
        return UINT16_MAX;
    }

    private static final int UINT32_MAX = (int) 4294967295L;

    /**
     * {@snippet lang = c:
     * #define UINT32_MAX 4294967295
     *}
     */
    public static int UINT32_MAX() {
        return UINT32_MAX;
    }

    private static final long UINT64_MAX = -1L;

    /**
     * {@snippet lang = c:
     * #define UINT64_MAX -1
     *}
     */
    public static long UINT64_MAX() {
        return UINT64_MAX;
    }

    private static final int INT_LEAST8_MIN = (int) -128L;

    /**
     * {@snippet lang = c:
     * #define INT_LEAST8_MIN -128
     *}
     */
    public static int INT_LEAST8_MIN() {
        return INT_LEAST8_MIN;
    }

    private static final int INT_LEAST16_MIN = (int) -32768L;

    /**
     * {@snippet lang = c:
     * #define INT_LEAST16_MIN -32768
     *}
     */
    public static int INT_LEAST16_MIN() {
        return INT_LEAST16_MIN;
    }

    private static final int INT_LEAST32_MIN = (int) -2147483648L;

    /**
     * {@snippet lang = c:
     * #define INT_LEAST32_MIN -2147483648
     *}
     */
    public static int INT_LEAST32_MIN() {
        return INT_LEAST32_MIN;
    }

    private static final long INT_LEAST64_MIN = -9223372036854775808L;

    /**
     * {@snippet lang = c:
     * #define INT_LEAST64_MIN -9223372036854775808
     *}
     */
    public static long INT_LEAST64_MIN() {
        return INT_LEAST64_MIN;
    }

    private static final byte INT_LEAST8_MAX = (byte) 127L;

    /**
     * {@snippet lang = c:
     * #define INT_LEAST8_MAX 127
     *}
     */
    public static byte INT_LEAST8_MAX() {
        return INT_LEAST8_MAX;
    }

    private static final short INT_LEAST16_MAX = (short) 32767L;

    /**
     * {@snippet lang = c:
     * #define INT_LEAST16_MAX 32767
     *}
     */
    public static short INT_LEAST16_MAX() {
        return INT_LEAST16_MAX;
    }

    private static final int INT_LEAST32_MAX = (int) 2147483647L;

    /**
     * {@snippet lang = c:
     * #define INT_LEAST32_MAX 2147483647
     *}
     */
    public static int INT_LEAST32_MAX() {
        return INT_LEAST32_MAX;
    }

    private static final long INT_LEAST64_MAX = 9223372036854775807L;

    /**
     * {@snippet lang = c:
     * #define INT_LEAST64_MAX 9223372036854775807
     *}
     */
    public static long INT_LEAST64_MAX() {
        return INT_LEAST64_MAX;
    }

    private static final byte UINT_LEAST8_MAX = (byte) 255L;

    /**
     * {@snippet lang = c:
     * #define UINT_LEAST8_MAX 255
     *}
     */
    public static byte UINT_LEAST8_MAX() {
        return UINT_LEAST8_MAX;
    }

    private static final short UINT_LEAST16_MAX = (short) 65535L;

    /**
     * {@snippet lang = c:
     * #define UINT_LEAST16_MAX 65535
     *}
     */
    public static short UINT_LEAST16_MAX() {
        return UINT_LEAST16_MAX;
    }

    private static final int UINT_LEAST32_MAX = (int) 4294967295L;

    /**
     * {@snippet lang = c:
     * #define UINT_LEAST32_MAX 4294967295
     *}
     */
    public static int UINT_LEAST32_MAX() {
        return UINT_LEAST32_MAX;
    }

    private static final long UINT_LEAST64_MAX = -1L;

    /**
     * {@snippet lang = c:
     * #define UINT_LEAST64_MAX -1
     *}
     */
    public static long UINT_LEAST64_MAX() {
        return UINT_LEAST64_MAX;
    }

    private static final int INT_FAST8_MIN = (int) -128L;

    /**
     * {@snippet lang = c:
     * #define INT_FAST8_MIN -128
     *}
     */
    public static int INT_FAST8_MIN() {
        return INT_FAST8_MIN;
    }

    private static final int INT_FAST16_MIN = (int) -2147483648L;

    /**
     * {@snippet lang = c:
     * #define INT_FAST16_MIN -2147483648
     *}
     */
    public static int INT_FAST16_MIN() {
        return INT_FAST16_MIN;
    }

    private static final int INT_FAST32_MIN = (int) -2147483648L;

    /**
     * {@snippet lang = c:
     * #define INT_FAST32_MIN -2147483648
     *}
     */
    public static int INT_FAST32_MIN() {
        return INT_FAST32_MIN;
    }

    private static final long INT_FAST64_MIN = -9223372036854775808L;

    /**
     * {@snippet lang = c:
     * #define INT_FAST64_MIN -9223372036854775808
     *}
     */
    public static long INT_FAST64_MIN() {
        return INT_FAST64_MIN;
    }

    private static final byte INT_FAST8_MAX = (byte) 127L;

    /**
     * {@snippet lang = c:
     * #define INT_FAST8_MAX 127
     *}
     */
    public static byte INT_FAST8_MAX() {
        return INT_FAST8_MAX;
    }

    private static final int INT_FAST16_MAX = (int) 2147483647L;

    /**
     * {@snippet lang = c:
     * #define INT_FAST16_MAX 2147483647
     *}
     */
    public static int INT_FAST16_MAX() {
        return INT_FAST16_MAX;
    }

    private static final int INT_FAST32_MAX = (int) 2147483647L;

    /**
     * {@snippet lang = c:
     * #define INT_FAST32_MAX 2147483647
     *}
     */
    public static int INT_FAST32_MAX() {
        return INT_FAST32_MAX;
    }

    private static final long INT_FAST64_MAX = 9223372036854775807L;

    /**
     * {@snippet lang = c:
     * #define INT_FAST64_MAX 9223372036854775807
     *}
     */
    public static long INT_FAST64_MAX() {
        return INT_FAST64_MAX;
    }

    private static final byte UINT_FAST8_MAX = (byte) 255L;

    /**
     * {@snippet lang = c:
     * #define UINT_FAST8_MAX 255
     *}
     */
    public static byte UINT_FAST8_MAX() {
        return UINT_FAST8_MAX;
    }

    private static final int UINT_FAST16_MAX = (int) 4294967295L;

    /**
     * {@snippet lang = c:
     * #define UINT_FAST16_MAX 4294967295
     *}
     */
    public static int UINT_FAST16_MAX() {
        return UINT_FAST16_MAX;
    }

    private static final int UINT_FAST32_MAX = (int) 4294967295L;

    /**
     * {@snippet lang = c:
     * #define UINT_FAST32_MAX 4294967295
     *}
     */
    public static int UINT_FAST32_MAX() {
        return UINT_FAST32_MAX;
    }

    private static final long UINT_FAST64_MAX = -1L;

    /**
     * {@snippet lang = c:
     * #define UINT_FAST64_MAX -1
     *}
     */
    public static long UINT_FAST64_MAX() {
        return UINT_FAST64_MAX;
    }

    private static final long INTPTR_MIN = -9223372036854775808L;

    /**
     * {@snippet lang = c:
     * #define INTPTR_MIN -9223372036854775808
     *}
     */
    public static long INTPTR_MIN() {
        return INTPTR_MIN;
    }

    private static final long INTPTR_MAX = 9223372036854775807L;

    /**
     * {@snippet lang = c:
     * #define INTPTR_MAX 9223372036854775807
     *}
     */
    public static long INTPTR_MAX() {
        return INTPTR_MAX;
    }

    private static final long UINTPTR_MAX = -1L;

    /**
     * {@snippet lang = c:
     * #define UINTPTR_MAX -1
     *}
     */
    public static long UINTPTR_MAX() {
        return UINTPTR_MAX;
    }

    private static final long INTMAX_MIN = -9223372036854775808L;

    /**
     * {@snippet lang = c:
     * #define INTMAX_MIN -9223372036854775808
     *}
     */
    public static long INTMAX_MIN() {
        return INTMAX_MIN;
    }

    private static final long INTMAX_MAX = 9223372036854775807L;

    /**
     * {@snippet lang = c:
     * #define INTMAX_MAX 9223372036854775807
     *}
     */
    public static long INTMAX_MAX() {
        return INTMAX_MAX;
    }

    private static final long UINTMAX_MAX = -1L;

    /**
     * {@snippet lang = c:
     * #define UINTMAX_MAX -1
     *}
     */
    public static long UINTMAX_MAX() {
        return UINTMAX_MAX;
    }

    private static final long PTRDIFF_MIN = -9223372036854775808L;

    /**
     * {@snippet lang = c:
     * #define PTRDIFF_MIN -9223372036854775808
     *}
     */
    public static long PTRDIFF_MIN() {
        return PTRDIFF_MIN;
    }

    private static final long PTRDIFF_MAX = 9223372036854775807L;

    /**
     * {@snippet lang = c:
     * #define PTRDIFF_MAX 9223372036854775807
     *}
     */
    public static long PTRDIFF_MAX() {
        return PTRDIFF_MAX;
    }

    private static final long SIZE_MAX = -1L;

    /**
     * {@snippet lang = c:
     * #define SIZE_MAX -1
     *}
     */
    public static long SIZE_MAX() {
        return SIZE_MAX;
    }

    private static final int SIG_ATOMIC_MIN = (int) -2147483648L;

    /**
     * {@snippet lang = c:
     * #define SIG_ATOMIC_MIN -2147483648
     *}
     */
    public static int SIG_ATOMIC_MIN() {
        return SIG_ATOMIC_MIN;
    }

    private static final int SIG_ATOMIC_MAX = (int) 2147483647L;

    /**
     * {@snippet lang = c:
     * #define SIG_ATOMIC_MAX 2147483647
     *}
     */
    public static int SIG_ATOMIC_MAX() {
        return SIG_ATOMIC_MAX;
    }
}

