// Generated by jextract

package sh.adelessfox.vgmstream.libvgmstream;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfBoolean;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct {
 *     void *buf;
 *     int buf_samples;
 *     int buf_bytes;
 *     _Bool done;
 * }
 *}
 */
public class libvgmstream_decoder_t {

    libvgmstream_decoder_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        libvgmstream_h.C_POINTER.withName("buf"),
        libvgmstream_h.C_INT.withName("buf_samples"),
        libvgmstream_h.C_INT.withName("buf_bytes"),
        libvgmstream_h.C_BOOL.withName("done"),
        MemoryLayout.paddingLayout(7)
    ).withName("$anon$148:9");

    /**
     * The layout of this struct
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout buf$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("buf"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * void *buf
     *}
     */
    public static AddressLayout buf$layout() {
        return buf$LAYOUT;
    }

    private static final long buf$OFFSET = $LAYOUT.byteOffset(groupElement("buf"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * void *buf
     *}
     */
    public static long buf$offset() {
        return buf$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * void *buf
     *}
     */
    public static MemorySegment buf(MemorySegment struct) {
        return struct.get(buf$LAYOUT, buf$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * void *buf
     *}
     */
    public static void buf(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(buf$LAYOUT, buf$OFFSET, fieldValue);
    }

    private static final OfInt buf_samples$LAYOUT = (OfInt) $LAYOUT.select(groupElement("buf_samples"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int buf_samples
     *}
     */
    public static OfInt buf_samples$layout() {
        return buf_samples$LAYOUT;
    }

    private static final long buf_samples$OFFSET = $LAYOUT.byteOffset(groupElement("buf_samples"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int buf_samples
     *}
     */
    public static long buf_samples$offset() {
        return buf_samples$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int buf_samples
     *}
     */
    public static int buf_samples(MemorySegment struct) {
        return struct.get(buf_samples$LAYOUT, buf_samples$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int buf_samples
     *}
     */
    public static void buf_samples(MemorySegment struct, int fieldValue) {
        struct.set(buf_samples$LAYOUT, buf_samples$OFFSET, fieldValue);
    }

    private static final OfInt buf_bytes$LAYOUT = (OfInt) $LAYOUT.select(groupElement("buf_bytes"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int buf_bytes
     *}
     */
    public static OfInt buf_bytes$layout() {
        return buf_bytes$LAYOUT;
    }

    private static final long buf_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("buf_bytes"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int buf_bytes
     *}
     */
    public static long buf_bytes$offset() {
        return buf_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int buf_bytes
     *}
     */
    public static int buf_bytes(MemorySegment struct) {
        return struct.get(buf_bytes$LAYOUT, buf_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int buf_bytes
     *}
     */
    public static void buf_bytes(MemorySegment struct, int fieldValue) {
        struct.set(buf_bytes$LAYOUT, buf_bytes$OFFSET, fieldValue);
    }

    private static final OfBoolean done$LAYOUT = (OfBoolean) $LAYOUT.select(groupElement("done"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * _Bool done
     *}
     */
    public static OfBoolean done$layout() {
        return done$LAYOUT;
    }

    private static final long done$OFFSET = $LAYOUT.byteOffset(groupElement("done"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * _Bool done
     *}
     */
    public static long done$offset() {
        return done$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * _Bool done
     *}
     */
    public static boolean done(MemorySegment struct) {
        return struct.get(done$LAYOUT, done$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * _Bool done
     *}
     */
    public static void done(MemorySegment struct, boolean fieldValue) {
        struct.set(done$LAYOUT, done$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() {
        return layout().byteSize();
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(
        MemorySegment addr,
        long elementCount,
        Arena arena,
        Consumer<MemorySegment> cleanup
    ) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

