// Generated by jextract

package sh.adelessfox.vgmstream.libvgmstream;

import java.lang.foreign.*;
import java.lang.invoke.VarHandle;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.MemoryLayout.PathElement.sequenceElement;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@snippet lang = c:
 * struct {
 *     int channels;
 *     int sample_rate;
 *     libvgmstream_sfmt_t sample_format;
 *     int sample_size;
 *     uint32_t channel_layout;
 *     int subsong_index;
 *     int subsong_count;
 *     int input_channels;
 *     int64_t stream_samples;
 *     int64_t loop_start;
 *     int64_t loop_end;
 *     _Bool loop_flag;
 *     _Bool play_forever;
 *     int64_t play_samples;
 *     int stream_bitrate;
 *     char codec_name[128];
 *     char layout_name[128];
 *     char meta_name[128];
 *     char stream_name[256];
 *     int format_id;
 * }
 *}
 */
public class libvgmstream_format_t {

    libvgmstream_format_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        libvgmstream_h.C_INT.withName("channels"),
        libvgmstream_h.C_INT.withName("sample_rate"),
        libvgmstream_h.C_INT.withName("sample_format"),
        libvgmstream_h.C_INT.withName("sample_size"),
        libvgmstream_h.C_INT.withName("channel_layout"),
        libvgmstream_h.C_INT.withName("subsong_index"),
        libvgmstream_h.C_INT.withName("subsong_count"),
        libvgmstream_h.C_INT.withName("input_channels"),
        libvgmstream_h.C_LONG_LONG.withName("stream_samples"),
        libvgmstream_h.C_LONG_LONG.withName("loop_start"),
        libvgmstream_h.C_LONG_LONG.withName("loop_end"),
        libvgmstream_h.C_BOOL.withName("loop_flag"),
        libvgmstream_h.C_BOOL.withName("play_forever"),
        MemoryLayout.paddingLayout(6),
        libvgmstream_h.C_LONG_LONG.withName("play_samples"),
        libvgmstream_h.C_INT.withName("stream_bitrate"),
        MemoryLayout.sequenceLayout(128, libvgmstream_h.C_CHAR).withName("codec_name"),
        MemoryLayout.sequenceLayout(128, libvgmstream_h.C_CHAR).withName("layout_name"),
        MemoryLayout.sequenceLayout(128, libvgmstream_h.C_CHAR).withName("meta_name"),
        MemoryLayout.sequenceLayout(256, libvgmstream_h.C_CHAR).withName("stream_name"),
        libvgmstream_h.C_INT.withName("format_id")
    ).withName("$anon$94:9");

    /**
     * The layout of this struct
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt channels$LAYOUT = (OfInt) $LAYOUT.select(groupElement("channels"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int channels
     *}
     */
    public static OfInt channels$layout() {
        return channels$LAYOUT;
    }

    private static final long channels$OFFSET = $LAYOUT.byteOffset(groupElement("channels"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int channels
     *}
     */
    public static long channels$offset() {
        return channels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int channels
     *}
     */
    public static int channels(MemorySegment struct) {
        return struct.get(channels$LAYOUT, channels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int channels
     *}
     */
    public static void channels(MemorySegment struct, int fieldValue) {
        struct.set(channels$LAYOUT, channels$OFFSET, fieldValue);
    }

    private static final OfInt sample_rate$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sample_rate"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int sample_rate
     *}
     */
    public static OfInt sample_rate$layout() {
        return sample_rate$LAYOUT;
    }

    private static final long sample_rate$OFFSET = $LAYOUT.byteOffset(groupElement("sample_rate"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int sample_rate
     *}
     */
    public static long sample_rate$offset() {
        return sample_rate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int sample_rate
     *}
     */
    public static int sample_rate(MemorySegment struct) {
        return struct.get(sample_rate$LAYOUT, sample_rate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int sample_rate
     *}
     */
    public static void sample_rate(MemorySegment struct, int fieldValue) {
        struct.set(sample_rate$LAYOUT, sample_rate$OFFSET, fieldValue);
    }

    private static final OfInt sample_format$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sample_format"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * libvgmstream_sfmt_t sample_format
     *}
     */
    public static OfInt sample_format$layout() {
        return sample_format$LAYOUT;
    }

    private static final long sample_format$OFFSET = $LAYOUT.byteOffset(groupElement("sample_format"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * libvgmstream_sfmt_t sample_format
     *}
     */
    public static long sample_format$offset() {
        return sample_format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * libvgmstream_sfmt_t sample_format
     *}
     */
    public static int sample_format(MemorySegment struct) {
        return struct.get(sample_format$LAYOUT, sample_format$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * libvgmstream_sfmt_t sample_format
     *}
     */
    public static void sample_format(MemorySegment struct, int fieldValue) {
        struct.set(sample_format$LAYOUT, sample_format$OFFSET, fieldValue);
    }

    private static final OfInt sample_size$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sample_size"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int sample_size
     *}
     */
    public static OfInt sample_size$layout() {
        return sample_size$LAYOUT;
    }

    private static final long sample_size$OFFSET = $LAYOUT.byteOffset(groupElement("sample_size"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int sample_size
     *}
     */
    public static long sample_size$offset() {
        return sample_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int sample_size
     *}
     */
    public static int sample_size(MemorySegment struct) {
        return struct.get(sample_size$LAYOUT, sample_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int sample_size
     *}
     */
    public static void sample_size(MemorySegment struct, int fieldValue) {
        struct.set(sample_size$LAYOUT, sample_size$OFFSET, fieldValue);
    }

    private static final OfInt channel_layout$LAYOUT = (OfInt) $LAYOUT.select(groupElement("channel_layout"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * uint32_t channel_layout
     *}
     */
    public static OfInt channel_layout$layout() {
        return channel_layout$LAYOUT;
    }

    private static final long channel_layout$OFFSET = $LAYOUT.byteOffset(groupElement("channel_layout"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * uint32_t channel_layout
     *}
     */
    public static long channel_layout$offset() {
        return channel_layout$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * uint32_t channel_layout
     *}
     */
    public static int channel_layout(MemorySegment struct) {
        return struct.get(channel_layout$LAYOUT, channel_layout$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * uint32_t channel_layout
     *}
     */
    public static void channel_layout(MemorySegment struct, int fieldValue) {
        struct.set(channel_layout$LAYOUT, channel_layout$OFFSET, fieldValue);
    }

    private static final OfInt subsong_index$LAYOUT = (OfInt) $LAYOUT.select(groupElement("subsong_index"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int subsong_index
     *}
     */
    public static OfInt subsong_index$layout() {
        return subsong_index$LAYOUT;
    }

    private static final long subsong_index$OFFSET = $LAYOUT.byteOffset(groupElement("subsong_index"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int subsong_index
     *}
     */
    public static long subsong_index$offset() {
        return subsong_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int subsong_index
     *}
     */
    public static int subsong_index(MemorySegment struct) {
        return struct.get(subsong_index$LAYOUT, subsong_index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int subsong_index
     *}
     */
    public static void subsong_index(MemorySegment struct, int fieldValue) {
        struct.set(subsong_index$LAYOUT, subsong_index$OFFSET, fieldValue);
    }

    private static final OfInt subsong_count$LAYOUT = (OfInt) $LAYOUT.select(groupElement("subsong_count"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int subsong_count
     *}
     */
    public static OfInt subsong_count$layout() {
        return subsong_count$LAYOUT;
    }

    private static final long subsong_count$OFFSET = $LAYOUT.byteOffset(groupElement("subsong_count"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int subsong_count
     *}
     */
    public static long subsong_count$offset() {
        return subsong_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int subsong_count
     *}
     */
    public static int subsong_count(MemorySegment struct) {
        return struct.get(subsong_count$LAYOUT, subsong_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int subsong_count
     *}
     */
    public static void subsong_count(MemorySegment struct, int fieldValue) {
        struct.set(subsong_count$LAYOUT, subsong_count$OFFSET, fieldValue);
    }

    private static final OfInt input_channels$LAYOUT = (OfInt) $LAYOUT.select(groupElement("input_channels"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int input_channels
     *}
     */
    public static OfInt input_channels$layout() {
        return input_channels$LAYOUT;
    }

    private static final long input_channels$OFFSET = $LAYOUT.byteOffset(groupElement("input_channels"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int input_channels
     *}
     */
    public static long input_channels$offset() {
        return input_channels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int input_channels
     *}
     */
    public static int input_channels(MemorySegment struct) {
        return struct.get(input_channels$LAYOUT, input_channels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int input_channels
     *}
     */
    public static void input_channels(MemorySegment struct, int fieldValue) {
        struct.set(input_channels$LAYOUT, input_channels$OFFSET, fieldValue);
    }

    private static final OfLong stream_samples$LAYOUT = (OfLong) $LAYOUT.select(groupElement("stream_samples"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int64_t stream_samples
     *}
     */
    public static OfLong stream_samples$layout() {
        return stream_samples$LAYOUT;
    }

    private static final long stream_samples$OFFSET = $LAYOUT.byteOffset(groupElement("stream_samples"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int64_t stream_samples
     *}
     */
    public static long stream_samples$offset() {
        return stream_samples$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int64_t stream_samples
     *}
     */
    public static long stream_samples(MemorySegment struct) {
        return struct.get(stream_samples$LAYOUT, stream_samples$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int64_t stream_samples
     *}
     */
    public static void stream_samples(MemorySegment struct, long fieldValue) {
        struct.set(stream_samples$LAYOUT, stream_samples$OFFSET, fieldValue);
    }

    private static final OfLong loop_start$LAYOUT = (OfLong) $LAYOUT.select(groupElement("loop_start"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int64_t loop_start
     *}
     */
    public static OfLong loop_start$layout() {
        return loop_start$LAYOUT;
    }

    private static final long loop_start$OFFSET = $LAYOUT.byteOffset(groupElement("loop_start"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int64_t loop_start
     *}
     */
    public static long loop_start$offset() {
        return loop_start$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int64_t loop_start
     *}
     */
    public static long loop_start(MemorySegment struct) {
        return struct.get(loop_start$LAYOUT, loop_start$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int64_t loop_start
     *}
     */
    public static void loop_start(MemorySegment struct, long fieldValue) {
        struct.set(loop_start$LAYOUT, loop_start$OFFSET, fieldValue);
    }

    private static final OfLong loop_end$LAYOUT = (OfLong) $LAYOUT.select(groupElement("loop_end"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int64_t loop_end
     *}
     */
    public static OfLong loop_end$layout() {
        return loop_end$LAYOUT;
    }

    private static final long loop_end$OFFSET = $LAYOUT.byteOffset(groupElement("loop_end"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int64_t loop_end
     *}
     */
    public static long loop_end$offset() {
        return loop_end$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int64_t loop_end
     *}
     */
    public static long loop_end(MemorySegment struct) {
        return struct.get(loop_end$LAYOUT, loop_end$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int64_t loop_end
     *}
     */
    public static void loop_end(MemorySegment struct, long fieldValue) {
        struct.set(loop_end$LAYOUT, loop_end$OFFSET, fieldValue);
    }

    private static final OfBoolean loop_flag$LAYOUT = (OfBoolean) $LAYOUT.select(groupElement("loop_flag"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * _Bool loop_flag
     *}
     */
    public static OfBoolean loop_flag$layout() {
        return loop_flag$LAYOUT;
    }

    private static final long loop_flag$OFFSET = $LAYOUT.byteOffset(groupElement("loop_flag"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * _Bool loop_flag
     *}
     */
    public static long loop_flag$offset() {
        return loop_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * _Bool loop_flag
     *}
     */
    public static boolean loop_flag(MemorySegment struct) {
        return struct.get(loop_flag$LAYOUT, loop_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * _Bool loop_flag
     *}
     */
    public static void loop_flag(MemorySegment struct, boolean fieldValue) {
        struct.set(loop_flag$LAYOUT, loop_flag$OFFSET, fieldValue);
    }

    private static final OfBoolean play_forever$LAYOUT = (OfBoolean) $LAYOUT.select(groupElement("play_forever"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * _Bool play_forever
     *}
     */
    public static OfBoolean play_forever$layout() {
        return play_forever$LAYOUT;
    }

    private static final long play_forever$OFFSET = $LAYOUT.byteOffset(groupElement("play_forever"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * _Bool play_forever
     *}
     */
    public static long play_forever$offset() {
        return play_forever$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * _Bool play_forever
     *}
     */
    public static boolean play_forever(MemorySegment struct) {
        return struct.get(play_forever$LAYOUT, play_forever$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * _Bool play_forever
     *}
     */
    public static void play_forever(MemorySegment struct, boolean fieldValue) {
        struct.set(play_forever$LAYOUT, play_forever$OFFSET, fieldValue);
    }

    private static final OfLong play_samples$LAYOUT = (OfLong) $LAYOUT.select(groupElement("play_samples"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int64_t play_samples
     *}
     */
    public static OfLong play_samples$layout() {
        return play_samples$LAYOUT;
    }

    private static final long play_samples$OFFSET = $LAYOUT.byteOffset(groupElement("play_samples"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int64_t play_samples
     *}
     */
    public static long play_samples$offset() {
        return play_samples$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int64_t play_samples
     *}
     */
    public static long play_samples(MemorySegment struct) {
        return struct.get(play_samples$LAYOUT, play_samples$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int64_t play_samples
     *}
     */
    public static void play_samples(MemorySegment struct, long fieldValue) {
        struct.set(play_samples$LAYOUT, play_samples$OFFSET, fieldValue);
    }

    private static final OfInt stream_bitrate$LAYOUT = (OfInt) $LAYOUT.select(groupElement("stream_bitrate"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int stream_bitrate
     *}
     */
    public static OfInt stream_bitrate$layout() {
        return stream_bitrate$LAYOUT;
    }

    private static final long stream_bitrate$OFFSET = $LAYOUT.byteOffset(groupElement("stream_bitrate"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int stream_bitrate
     *}
     */
    public static long stream_bitrate$offset() {
        return stream_bitrate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int stream_bitrate
     *}
     */
    public static int stream_bitrate(MemorySegment struct) {
        return struct.get(stream_bitrate$LAYOUT, stream_bitrate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int stream_bitrate
     *}
     */
    public static void stream_bitrate(MemorySegment struct, int fieldValue) {
        struct.set(stream_bitrate$LAYOUT, stream_bitrate$OFFSET, fieldValue);
    }

    private static final SequenceLayout codec_name$LAYOUT = (SequenceLayout) $LAYOUT.select(groupElement("codec_name"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * char codec_name[128]
     *}
     */
    public static SequenceLayout codec_name$layout() {
        return codec_name$LAYOUT;
    }

    private static final long codec_name$OFFSET = $LAYOUT.byteOffset(groupElement("codec_name"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * char codec_name[128]
     *}
     */
    public static long codec_name$offset() {
        return codec_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * char codec_name[128]
     *}
     */
    public static MemorySegment codec_name(MemorySegment struct) {
        return struct.asSlice(codec_name$OFFSET, codec_name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * char codec_name[128]
     *}
     */
    public static void codec_name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, codec_name$OFFSET, codec_name$LAYOUT.byteSize());
    }

    private static long[] codec_name$DIMS = {128};

    /**
     * Dimensions for array field:
     * {@snippet lang = c:
     * char codec_name[128]
     *}
     */
    public static long[] codec_name$dimensions() {
        return codec_name$DIMS;
    }

    private static final VarHandle codec_name$ELEM_HANDLE = codec_name$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang = c:
     * char codec_name[128]
     *}
     */
    public static byte codec_name(MemorySegment struct, long index0) {
        return (byte) codec_name$ELEM_HANDLE.get(struct, codec_name$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang = c:
     * char codec_name[128]
     *}
     */
    public static void codec_name(MemorySegment struct, long index0, byte fieldValue) {
        codec_name$ELEM_HANDLE.set(struct, codec_name$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout layout_name$LAYOUT = (SequenceLayout) $LAYOUT.select(groupElement("layout_name"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * char layout_name[128]
     *}
     */
    public static SequenceLayout layout_name$layout() {
        return layout_name$LAYOUT;
    }

    private static final long layout_name$OFFSET = $LAYOUT.byteOffset(groupElement("layout_name"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * char layout_name[128]
     *}
     */
    public static long layout_name$offset() {
        return layout_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * char layout_name[128]
     *}
     */
    public static MemorySegment layout_name(MemorySegment struct) {
        return struct.asSlice(layout_name$OFFSET, layout_name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * char layout_name[128]
     *}
     */
    public static void layout_name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, layout_name$OFFSET, layout_name$LAYOUT.byteSize());
    }

    private static long[] layout_name$DIMS = {128};

    /**
     * Dimensions for array field:
     * {@snippet lang = c:
     * char layout_name[128]
     *}
     */
    public static long[] layout_name$dimensions() {
        return layout_name$DIMS;
    }

    private static final VarHandle layout_name$ELEM_HANDLE = layout_name$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang = c:
     * char layout_name[128]
     *}
     */
    public static byte layout_name(MemorySegment struct, long index0) {
        return (byte) layout_name$ELEM_HANDLE.get(struct, layout_name$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang = c:
     * char layout_name[128]
     *}
     */
    public static void layout_name(MemorySegment struct, long index0, byte fieldValue) {
        layout_name$ELEM_HANDLE.set(struct, layout_name$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout meta_name$LAYOUT = (SequenceLayout) $LAYOUT.select(groupElement("meta_name"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * char meta_name[128]
     *}
     */
    public static SequenceLayout meta_name$layout() {
        return meta_name$LAYOUT;
    }

    private static final long meta_name$OFFSET = $LAYOUT.byteOffset(groupElement("meta_name"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * char meta_name[128]
     *}
     */
    public static long meta_name$offset() {
        return meta_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * char meta_name[128]
     *}
     */
    public static MemorySegment meta_name(MemorySegment struct) {
        return struct.asSlice(meta_name$OFFSET, meta_name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * char meta_name[128]
     *}
     */
    public static void meta_name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, meta_name$OFFSET, meta_name$LAYOUT.byteSize());
    }

    private static long[] meta_name$DIMS = {128};

    /**
     * Dimensions for array field:
     * {@snippet lang = c:
     * char meta_name[128]
     *}
     */
    public static long[] meta_name$dimensions() {
        return meta_name$DIMS;
    }

    private static final VarHandle meta_name$ELEM_HANDLE = meta_name$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang = c:
     * char meta_name[128]
     *}
     */
    public static byte meta_name(MemorySegment struct, long index0) {
        return (byte) meta_name$ELEM_HANDLE.get(struct, meta_name$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang = c:
     * char meta_name[128]
     *}
     */
    public static void meta_name(MemorySegment struct, long index0, byte fieldValue) {
        meta_name$ELEM_HANDLE.set(struct, meta_name$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout stream_name$LAYOUT = (SequenceLayout) $LAYOUT.select(groupElement("stream_name"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * char stream_name[256]
     *}
     */
    public static SequenceLayout stream_name$layout() {
        return stream_name$LAYOUT;
    }

    private static final long stream_name$OFFSET = $LAYOUT.byteOffset(groupElement("stream_name"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * char stream_name[256]
     *}
     */
    public static long stream_name$offset() {
        return stream_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * char stream_name[256]
     *}
     */
    public static MemorySegment stream_name(MemorySegment struct) {
        return struct.asSlice(stream_name$OFFSET, stream_name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * char stream_name[256]
     *}
     */
    public static void stream_name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, stream_name$OFFSET, stream_name$LAYOUT.byteSize());
    }

    private static long[] stream_name$DIMS = {256};

    /**
     * Dimensions for array field:
     * {@snippet lang = c:
     * char stream_name[256]
     *}
     */
    public static long[] stream_name$dimensions() {
        return stream_name$DIMS;
    }

    private static final VarHandle stream_name$ELEM_HANDLE = stream_name$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang = c:
     * char stream_name[256]
     *}
     */
    public static byte stream_name(MemorySegment struct, long index0) {
        return (byte) stream_name$ELEM_HANDLE.get(struct, stream_name$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang = c:
     * char stream_name[256]
     *}
     */
    public static void stream_name(MemorySegment struct, long index0, byte fieldValue) {
        stream_name$ELEM_HANDLE.set(struct, stream_name$OFFSET, index0, fieldValue);
    }

    private static final OfInt format_id$LAYOUT = (OfInt) $LAYOUT.select(groupElement("format_id"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int format_id
     *}
     */
    public static OfInt format_id$layout() {
        return format_id$LAYOUT;
    }

    private static final long format_id$OFFSET = $LAYOUT.byteOffset(groupElement("format_id"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int format_id
     *}
     */
    public static long format_id$offset() {
        return format_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int format_id
     *}
     */
    public static int format_id(MemorySegment struct) {
        return struct.get(format_id$LAYOUT, format_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int format_id
     *}
     */
    public static void format_id(MemorySegment struct, int fieldValue) {
        struct.set(format_id$LAYOUT, format_id$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() {
        return layout().byteSize();
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(
        MemorySegment addr,
        long elementCount,
        Arena arena,
        Consumer<MemorySegment> cleanup
    ) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

