// Generated by jextract

package sh.adelessfox.vgmstream.libvgmstream;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@snippet lang = c:
 * struct {
 *     _Bool disable_config_override;
 *     _Bool allow_play_forever;
 *     _Bool play_forever;
 *     _Bool ignore_loop;
 *     _Bool force_loop;
 *     _Bool really_force_loop;
 *     _Bool ignore_fade;
 *     double loop_count;
 *     double fade_time;
 *     double fade_delay;
 *     int stereo_track;
 *     int auto_downmix_channels;
 *     libvgmstream_sfmt_t force_sfmt;
 * }
 *}
 */
public class libvgmstream_config_t {

    libvgmstream_config_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        libvgmstream_h.C_BOOL.withName("disable_config_override"),
        libvgmstream_h.C_BOOL.withName("allow_play_forever"),
        libvgmstream_h.C_BOOL.withName("play_forever"),
        libvgmstream_h.C_BOOL.withName("ignore_loop"),
        libvgmstream_h.C_BOOL.withName("force_loop"),
        libvgmstream_h.C_BOOL.withName("really_force_loop"),
        libvgmstream_h.C_BOOL.withName("ignore_fade"),
        MemoryLayout.paddingLayout(1),
        libvgmstream_h.C_DOUBLE.withName("loop_count"),
        libvgmstream_h.C_DOUBLE.withName("fade_time"),
        libvgmstream_h.C_DOUBLE.withName("fade_delay"),
        libvgmstream_h.C_INT.withName("stereo_track"),
        libvgmstream_h.C_INT.withName("auto_downmix_channels"),
        libvgmstream_h.C_INT.withName("force_sfmt"),
        MemoryLayout.paddingLayout(4)
    ).withName("$anon$180:9");

    /**
     * The layout of this struct
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfBoolean disable_config_override$LAYOUT = (OfBoolean) $LAYOUT.select(groupElement("disable_config_override"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * _Bool disable_config_override
     *}
     */
    public static OfBoolean disable_config_override$layout() {
        return disable_config_override$LAYOUT;
    }

    private static final long disable_config_override$OFFSET = $LAYOUT.byteOffset(groupElement("disable_config_override"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * _Bool disable_config_override
     *}
     */
    public static long disable_config_override$offset() {
        return disable_config_override$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * _Bool disable_config_override
     *}
     */
    public static boolean disable_config_override(MemorySegment struct) {
        return struct.get(disable_config_override$LAYOUT, disable_config_override$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * _Bool disable_config_override
     *}
     */
    public static void disable_config_override(MemorySegment struct, boolean fieldValue) {
        struct.set(disable_config_override$LAYOUT, disable_config_override$OFFSET, fieldValue);
    }

    private static final OfBoolean allow_play_forever$LAYOUT = (OfBoolean) $LAYOUT.select(groupElement("allow_play_forever"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * _Bool allow_play_forever
     *}
     */
    public static OfBoolean allow_play_forever$layout() {
        return allow_play_forever$LAYOUT;
    }

    private static final long allow_play_forever$OFFSET = $LAYOUT.byteOffset(groupElement("allow_play_forever"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * _Bool allow_play_forever
     *}
     */
    public static long allow_play_forever$offset() {
        return allow_play_forever$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * _Bool allow_play_forever
     *}
     */
    public static boolean allow_play_forever(MemorySegment struct) {
        return struct.get(allow_play_forever$LAYOUT, allow_play_forever$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * _Bool allow_play_forever
     *}
     */
    public static void allow_play_forever(MemorySegment struct, boolean fieldValue) {
        struct.set(allow_play_forever$LAYOUT, allow_play_forever$OFFSET, fieldValue);
    }

    private static final OfBoolean play_forever$LAYOUT = (OfBoolean) $LAYOUT.select(groupElement("play_forever"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * _Bool play_forever
     *}
     */
    public static OfBoolean play_forever$layout() {
        return play_forever$LAYOUT;
    }

    private static final long play_forever$OFFSET = $LAYOUT.byteOffset(groupElement("play_forever"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * _Bool play_forever
     *}
     */
    public static long play_forever$offset() {
        return play_forever$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * _Bool play_forever
     *}
     */
    public static boolean play_forever(MemorySegment struct) {
        return struct.get(play_forever$LAYOUT, play_forever$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * _Bool play_forever
     *}
     */
    public static void play_forever(MemorySegment struct, boolean fieldValue) {
        struct.set(play_forever$LAYOUT, play_forever$OFFSET, fieldValue);
    }

    private static final OfBoolean ignore_loop$LAYOUT = (OfBoolean) $LAYOUT.select(groupElement("ignore_loop"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * _Bool ignore_loop
     *}
     */
    public static OfBoolean ignore_loop$layout() {
        return ignore_loop$LAYOUT;
    }

    private static final long ignore_loop$OFFSET = $LAYOUT.byteOffset(groupElement("ignore_loop"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * _Bool ignore_loop
     *}
     */
    public static long ignore_loop$offset() {
        return ignore_loop$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * _Bool ignore_loop
     *}
     */
    public static boolean ignore_loop(MemorySegment struct) {
        return struct.get(ignore_loop$LAYOUT, ignore_loop$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * _Bool ignore_loop
     *}
     */
    public static void ignore_loop(MemorySegment struct, boolean fieldValue) {
        struct.set(ignore_loop$LAYOUT, ignore_loop$OFFSET, fieldValue);
    }

    private static final OfBoolean force_loop$LAYOUT = (OfBoolean) $LAYOUT.select(groupElement("force_loop"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * _Bool force_loop
     *}
     */
    public static OfBoolean force_loop$layout() {
        return force_loop$LAYOUT;
    }

    private static final long force_loop$OFFSET = $LAYOUT.byteOffset(groupElement("force_loop"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * _Bool force_loop
     *}
     */
    public static long force_loop$offset() {
        return force_loop$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * _Bool force_loop
     *}
     */
    public static boolean force_loop(MemorySegment struct) {
        return struct.get(force_loop$LAYOUT, force_loop$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * _Bool force_loop
     *}
     */
    public static void force_loop(MemorySegment struct, boolean fieldValue) {
        struct.set(force_loop$LAYOUT, force_loop$OFFSET, fieldValue);
    }

    private static final OfBoolean really_force_loop$LAYOUT = (OfBoolean) $LAYOUT.select(groupElement("really_force_loop"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * _Bool really_force_loop
     *}
     */
    public static OfBoolean really_force_loop$layout() {
        return really_force_loop$LAYOUT;
    }

    private static final long really_force_loop$OFFSET = $LAYOUT.byteOffset(groupElement("really_force_loop"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * _Bool really_force_loop
     *}
     */
    public static long really_force_loop$offset() {
        return really_force_loop$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * _Bool really_force_loop
     *}
     */
    public static boolean really_force_loop(MemorySegment struct) {
        return struct.get(really_force_loop$LAYOUT, really_force_loop$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * _Bool really_force_loop
     *}
     */
    public static void really_force_loop(MemorySegment struct, boolean fieldValue) {
        struct.set(really_force_loop$LAYOUT, really_force_loop$OFFSET, fieldValue);
    }

    private static final OfBoolean ignore_fade$LAYOUT = (OfBoolean) $LAYOUT.select(groupElement("ignore_fade"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * _Bool ignore_fade
     *}
     */
    public static OfBoolean ignore_fade$layout() {
        return ignore_fade$LAYOUT;
    }

    private static final long ignore_fade$OFFSET = $LAYOUT.byteOffset(groupElement("ignore_fade"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * _Bool ignore_fade
     *}
     */
    public static long ignore_fade$offset() {
        return ignore_fade$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * _Bool ignore_fade
     *}
     */
    public static boolean ignore_fade(MemorySegment struct) {
        return struct.get(ignore_fade$LAYOUT, ignore_fade$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * _Bool ignore_fade
     *}
     */
    public static void ignore_fade(MemorySegment struct, boolean fieldValue) {
        struct.set(ignore_fade$LAYOUT, ignore_fade$OFFSET, fieldValue);
    }

    private static final OfDouble loop_count$LAYOUT = (OfDouble) $LAYOUT.select(groupElement("loop_count"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * double loop_count
     *}
     */
    public static OfDouble loop_count$layout() {
        return loop_count$LAYOUT;
    }

    private static final long loop_count$OFFSET = $LAYOUT.byteOffset(groupElement("loop_count"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * double loop_count
     *}
     */
    public static long loop_count$offset() {
        return loop_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * double loop_count
     *}
     */
    public static double loop_count(MemorySegment struct) {
        return struct.get(loop_count$LAYOUT, loop_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * double loop_count
     *}
     */
    public static void loop_count(MemorySegment struct, double fieldValue) {
        struct.set(loop_count$LAYOUT, loop_count$OFFSET, fieldValue);
    }

    private static final OfDouble fade_time$LAYOUT = (OfDouble) $LAYOUT.select(groupElement("fade_time"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * double fade_time
     *}
     */
    public static OfDouble fade_time$layout() {
        return fade_time$LAYOUT;
    }

    private static final long fade_time$OFFSET = $LAYOUT.byteOffset(groupElement("fade_time"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * double fade_time
     *}
     */
    public static long fade_time$offset() {
        return fade_time$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * double fade_time
     *}
     */
    public static double fade_time(MemorySegment struct) {
        return struct.get(fade_time$LAYOUT, fade_time$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * double fade_time
     *}
     */
    public static void fade_time(MemorySegment struct, double fieldValue) {
        struct.set(fade_time$LAYOUT, fade_time$OFFSET, fieldValue);
    }

    private static final OfDouble fade_delay$LAYOUT = (OfDouble) $LAYOUT.select(groupElement("fade_delay"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * double fade_delay
     *}
     */
    public static OfDouble fade_delay$layout() {
        return fade_delay$LAYOUT;
    }

    private static final long fade_delay$OFFSET = $LAYOUT.byteOffset(groupElement("fade_delay"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * double fade_delay
     *}
     */
    public static long fade_delay$offset() {
        return fade_delay$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * double fade_delay
     *}
     */
    public static double fade_delay(MemorySegment struct) {
        return struct.get(fade_delay$LAYOUT, fade_delay$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * double fade_delay
     *}
     */
    public static void fade_delay(MemorySegment struct, double fieldValue) {
        struct.set(fade_delay$LAYOUT, fade_delay$OFFSET, fieldValue);
    }

    private static final OfInt stereo_track$LAYOUT = (OfInt) $LAYOUT.select(groupElement("stereo_track"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int stereo_track
     *}
     */
    public static OfInt stereo_track$layout() {
        return stereo_track$LAYOUT;
    }

    private static final long stereo_track$OFFSET = $LAYOUT.byteOffset(groupElement("stereo_track"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int stereo_track
     *}
     */
    public static long stereo_track$offset() {
        return stereo_track$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int stereo_track
     *}
     */
    public static int stereo_track(MemorySegment struct) {
        return struct.get(stereo_track$LAYOUT, stereo_track$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int stereo_track
     *}
     */
    public static void stereo_track(MemorySegment struct, int fieldValue) {
        struct.set(stereo_track$LAYOUT, stereo_track$OFFSET, fieldValue);
    }

    private static final OfInt auto_downmix_channels$LAYOUT = (OfInt) $LAYOUT.select(groupElement("auto_downmix_channels"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * int auto_downmix_channels
     *}
     */
    public static OfInt auto_downmix_channels$layout() {
        return auto_downmix_channels$LAYOUT;
    }

    private static final long auto_downmix_channels$OFFSET = $LAYOUT.byteOffset(groupElement("auto_downmix_channels"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * int auto_downmix_channels
     *}
     */
    public static long auto_downmix_channels$offset() {
        return auto_downmix_channels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * int auto_downmix_channels
     *}
     */
    public static int auto_downmix_channels(MemorySegment struct) {
        return struct.get(auto_downmix_channels$LAYOUT, auto_downmix_channels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * int auto_downmix_channels
     *}
     */
    public static void auto_downmix_channels(MemorySegment struct, int fieldValue) {
        struct.set(auto_downmix_channels$LAYOUT, auto_downmix_channels$OFFSET, fieldValue);
    }

    private static final OfInt force_sfmt$LAYOUT = (OfInt) $LAYOUT.select(groupElement("force_sfmt"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * libvgmstream_sfmt_t force_sfmt
     *}
     */
    public static OfInt force_sfmt$layout() {
        return force_sfmt$LAYOUT;
    }

    private static final long force_sfmt$OFFSET = $LAYOUT.byteOffset(groupElement("force_sfmt"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * libvgmstream_sfmt_t force_sfmt
     *}
     */
    public static long force_sfmt$offset() {
        return force_sfmt$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * libvgmstream_sfmt_t force_sfmt
     *}
     */
    public static int force_sfmt(MemorySegment struct) {
        return struct.get(force_sfmt$LAYOUT, force_sfmt$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * libvgmstream_sfmt_t force_sfmt
     *}
     */
    public static void force_sfmt(MemorySegment struct, int fieldValue) {
        struct.set(force_sfmt$LAYOUT, force_sfmt$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() {
        return layout().byteSize();
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(
        MemorySegment addr,
        long elementCount,
        Arena arena,
        Consumer<MemorySegment> cleanup
    ) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

