// Generated by jextract

package sh.adelessfox.vgmstream.libvgmstream;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfBoolean;

/**
 * {@snippet lang=c :
 * struct {
 *     _Bool is_extension;
 *     _Bool skip_standard;
 *     _Bool reject_extensionless;
 *     _Bool accept_unknown;
 *     _Bool accept_common;
 * }
 * }
 */
public class libvgmstream_valid_t {

    libvgmstream_valid_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        libvgmstream_h.C_BOOL.withName("is_extension"),
        libvgmstream_h.C_BOOL.withName("skip_standard"),
        libvgmstream_h.C_BOOL.withName("reject_extensionless"),
        libvgmstream_h.C_BOOL.withName("accept_unknown"),
        libvgmstream_h.C_BOOL.withName("accept_common")
    ).withName("$anon$295:9");

    /**
     * The layout of this struct
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfBoolean is_extension$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("is_extension"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool is_extension
     * }
     */
    public static OfBoolean is_extension$layout() {
        return is_extension$LAYOUT;
    }

    private static final long is_extension$OFFSET = $LAYOUT.byteOffset(groupElement("is_extension"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool is_extension
     * }
     */
    public static long is_extension$offset() {
        return is_extension$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool is_extension
     * }
     */
    public static boolean is_extension(MemorySegment struct) {
        return struct.get(is_extension$LAYOUT, is_extension$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool is_extension
     * }
     */
    public static void is_extension(MemorySegment struct, boolean fieldValue) {
        struct.set(is_extension$LAYOUT, is_extension$OFFSET, fieldValue);
    }

    private static final OfBoolean skip_standard$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("skip_standard"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool skip_standard
     * }
     */
    public static OfBoolean skip_standard$layout() {
        return skip_standard$LAYOUT;
    }

    private static final long skip_standard$OFFSET = $LAYOUT.byteOffset(groupElement("skip_standard"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool skip_standard
     * }
     */
    public static long skip_standard$offset() {
        return skip_standard$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool skip_standard
     * }
     */
    public static boolean skip_standard(MemorySegment struct) {
        return struct.get(skip_standard$LAYOUT, skip_standard$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool skip_standard
     * }
     */
    public static void skip_standard(MemorySegment struct, boolean fieldValue) {
        struct.set(skip_standard$LAYOUT, skip_standard$OFFSET, fieldValue);
    }

    private static final OfBoolean reject_extensionless$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("reject_extensionless"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool reject_extensionless
     * }
     */
    public static OfBoolean reject_extensionless$layout() {
        return reject_extensionless$LAYOUT;
    }

    private static final long reject_extensionless$OFFSET = $LAYOUT.byteOffset(groupElement("reject_extensionless"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool reject_extensionless
     * }
     */
    public static long reject_extensionless$offset() {
        return reject_extensionless$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool reject_extensionless
     * }
     */
    public static boolean reject_extensionless(MemorySegment struct) {
        return struct.get(reject_extensionless$LAYOUT, reject_extensionless$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool reject_extensionless
     * }
     */
    public static void reject_extensionless(MemorySegment struct, boolean fieldValue) {
        struct.set(reject_extensionless$LAYOUT, reject_extensionless$OFFSET, fieldValue);
    }

    private static final OfBoolean accept_unknown$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("accept_unknown"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool accept_unknown
     * }
     */
    public static OfBoolean accept_unknown$layout() {
        return accept_unknown$LAYOUT;
    }

    private static final long accept_unknown$OFFSET = $LAYOUT.byteOffset(groupElement("accept_unknown"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool accept_unknown
     * }
     */
    public static long accept_unknown$offset() {
        return accept_unknown$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool accept_unknown
     * }
     */
    public static boolean accept_unknown(MemorySegment struct) {
        return struct.get(accept_unknown$LAYOUT, accept_unknown$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool accept_unknown
     * }
     */
    public static void accept_unknown(MemorySegment struct, boolean fieldValue) {
        struct.set(accept_unknown$LAYOUT, accept_unknown$OFFSET, fieldValue);
    }

    private static final OfBoolean accept_common$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("accept_common"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool accept_common
     * }
     */
    public static OfBoolean accept_common$layout() {
        return accept_common$LAYOUT;
    }

    private static final long accept_common$OFFSET = $LAYOUT.byteOffset(groupElement("accept_common"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool accept_common
     * }
     */
    public static long accept_common$offset() {
        return accept_common$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool accept_common
     * }
     */
    public static boolean accept_common(MemorySegment struct) {
        return struct.get(accept_common$LAYOUT, accept_common$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool accept_common
     * }
     */
    public static void accept_common(MemorySegment struct, boolean fieldValue) {
        struct.set(accept_common$LAYOUT, accept_common$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

