// Generated by jextract

package sh.adelessfox.vgmstream.libvgmstream;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;

/**
 * {@snippet lang = c:
 * struct {
 *     void *priv;
 *     const libvgmstream_format_t *format;
 *     libvgmstream_decoder_t *decoder;
 * }
 *}
 */
public class libvgmstream_t {

    libvgmstream_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        libvgmstream_h.C_POINTER.withName("priv"),
        libvgmstream_h.C_POINTER.withName("format"),
        libvgmstream_h.C_POINTER.withName("decoder")
    ).withName("$anon$158:9");

    /**
     * The layout of this struct
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout priv$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("priv"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * void *priv
     *}
     */
    public static AddressLayout priv$layout() {
        return priv$LAYOUT;
    }

    private static final long priv$OFFSET = $LAYOUT.byteOffset(groupElement("priv"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * void *priv
     *}
     */
    public static long priv$offset() {
        return priv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * void *priv
     *}
     */
    public static MemorySegment priv(MemorySegment struct) {
        return struct.get(priv$LAYOUT, priv$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * void *priv
     *}
     */
    public static void priv(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(priv$LAYOUT, priv$OFFSET, fieldValue);
    }

    private static final AddressLayout format$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("format"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * const libvgmstream_format_t *format
     *}
     */
    public static AddressLayout format$layout() {
        return format$LAYOUT;
    }

    private static final long format$OFFSET = $LAYOUT.byteOffset(groupElement("format"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * const libvgmstream_format_t *format
     *}
     */
    public static long format$offset() {
        return format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * const libvgmstream_format_t *format
     *}
     */
    public static MemorySegment format(MemorySegment struct) {
        return struct.get(format$LAYOUT, format$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * const libvgmstream_format_t *format
     *}
     */
    public static void format(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(format$LAYOUT, format$OFFSET, fieldValue);
    }

    private static final AddressLayout decoder$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("decoder"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * libvgmstream_decoder_t *decoder
     *}
     */
    public static AddressLayout decoder$layout() {
        return decoder$LAYOUT;
    }

    private static final long decoder$OFFSET = $LAYOUT.byteOffset(groupElement("decoder"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * libvgmstream_decoder_t *decoder
     *}
     */
    public static long decoder$offset() {
        return decoder$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * libvgmstream_decoder_t *decoder
     *}
     */
    public static MemorySegment decoder(MemorySegment struct) {
        return struct.get(decoder$LAYOUT, decoder$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * libvgmstream_decoder_t *decoder
     *}
     */
    public static void decoder(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(decoder$LAYOUT, decoder$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() {
        return layout().byteSize();
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(
        MemorySegment addr,
        long elementCount,
        Arena arena,
        Consumer<MemorySegment> cleanup
    ) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

