AudioWaveform.background = @componentBackground
AudioWaveform.peak.background = @accentBase2Color
AudioWaveform.peak.dim.background = lighten($AudioWaveform.peak.background,25%)
AudioWaveform.peak.width = 2
AudioWaveform.peak.horizontalGap = 1
AudioWaveform.peak.verticalGap = 2
