FlatLaf.experimental.tree.widePathForLocation = true

# UI Delegates
ToolTipUI = sh.adelessfox.odradek.ui.components.laf.FlatOutlineToolTipUI
SplitButtonUI = sh.adelessfox.odradek.ui.components.laf.FlatSplitButtonUI
LabeledSeparatorUI = sh.adelessfox.odradek.ui.components.laf.FlatLabeledSeparatorUI

TitlePane.useWindowDecorations = true
TitlePane.unifiedBackground = true

Component.hideMnemonics = false
TabbedPane.tabHeight = 28
TabbedPane.tabRotation = auto
TabbedPane.tabType = card
SplitPane.dividerSize = 7
SplitPaneDivider.style = plain
ScrollPane.border = 0,0,0,0
Tree.rowHeight = 24
Tree.border = 0,8,0,8
Button.toolbar.spacingInsets = 2,2,2,2
Button.toolbar.margin = 2,2,2,2

Component.error.borderColor = #fad4d8
Component.error.background = lighten($Component.error.borderColor, 4%)
Component.warning.borderColor = #fedd77
Component.warning.background = lighten($Component.warning.borderColor, 15%)

SplitButton.arrowColor = @buttonArrowColor
SplitButton.arrowWidth = 7
SplitButton.arrowGap = 4

LabeledSeparator.labelForeground = @foreground

StyledFragment.nameForeground = #800000
StyledFragment.numberForeground = #0000ff
StyledFragment.stringForeground = #008000

EditorStack.overlay.background = fade(@selectionBackground, 50%)
EditorStack.overlay.borderColor = lighten(@selectionBackground, 20%)

TextSearchSupport.currentMatchBackground = lighten(@selectionBackground, 20%)
TextSearchSupport.matchBackground = mix(@selectionBackground, @disabledBackground, 20%)

Editor.background = @componentBackground

ToolPanel.borderColor = $Component.borderColor
ToolPanel.focusedBorderColor = mix($ToolPanel.borderColor, $TabbedPane.underlineColor, 50%)
ToolPanel.background = $@componentBackground
ToolPanel.header.height = $TabbedPane.tabHeight
ToolPanel.header.backgroundStart = @componentBackground
ToolPanel.header.backgroundEnd = darken(@componentBackground, 5%)

ToolButton.margin = 4,4,4,4
ToolButton.arc = {scaledInteger}10
ToolButton.textIconGap = {scaledInteger}4
ToolButton.background = $Panel.background
ToolButton.hoverBackground = $Button.pressedBackground
ToolButton.selectedBackground = $Button.pressedBackground
ToolButton.focusedBackground = mix($Panel.background, $Button.focusedBorderColor, 70%)
ToolButton.borderColor = $ToolButton.background
ToolButton.selectedBorderColor = $Component.borderColor
ToolButton.focusedBorderColor = $ToolPanel.focusedBorderColor

[style]Button.inTextField = \
	focusable: false; \
	toolbar.margin: 2,2,2,2; \
	toolbar.spacingInsets: 1,1,1,1;
