FlatLaf.experimental.tree.widePathForLocation = true

# UI Delegates
ToolTipUI = sh.adelessfox.odradek.ui.components.laf.FlatOutlineToolTipUI

TitlePane.useWindowDecorations = true
TitlePane.unifiedBackground = true

Component.hideMnemonics = false
TabbedPane.tabHeight = 28
TabbedPane.tabRotation = auto
TabbedPane.tabType = card
SplitPane.dividerSize = 7
SplitPaneDivider.style = plain
ScrollPane.border = 0,0,0,0
Tree.rowHeight = 24
Tree.border = 0,8,0,8
Button.toolbar.spacingInsets = 2,2,2,2
Button.toolbar.margin = 2,2,2,2

Component.error.borderColor = #fad4d8
Component.error.background = lighten($Component.error.borderColor, 4%)
Component.warning.borderColor = #fedd77
Component.warning.background = lighten($Component.warning.borderColor, 15%)

ToolPanelButton.size = {scaledDimension}32,32
ToolPanelButton.margin = {scaledInsets}4,4,4,4
ToolPanelButton.arc = {scaledInteger}10
ToolPanelButton.background = $Button.default.hoverBackground
ToolPanelButton.selectedBackground = $Button.selectedBackground
ToolPanelButton.focusedSelectedColor = $Button.default.borderColor
ToolPanelButton.rolloverBackground = $Button.default.pressedBackground

StyledFragment.nameForeground = #800000
StyledFragment.numberForeground = #0000ff
StyledFragment.stringForeground = #008000

EditorStack.overlay.background = fade(@selectionBackground, 50%)
EditorStack.overlay.borderColor = lighten(@selectionBackground, 20%)

[style]Button.inTextField = \
	focusable: false; \
	toolbar.margin: 2,2,2,2; \
	toolbar.spacingInsets: 1,1,1,1;
